# Site settings
title: Elvin Shrestha
description: Elvin Shrestha's Curriculum Vitae
favicon: /assets/img/avatar.JPG
baseurl: https://elwyncrestha.github.io
url: https://elwyncrestha.github.io
rss_url: /pages/atom.xml
google_analytics: UA-132466874-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Elvin Shrestha
  title: Student
  address: Tahachal-13, Kathmandu, Nepal
  blogLink: https://elwyncrestha.github.io/elwyncrestha-blog/
  email: elwyncrestha@gmail.com
  link: https://elwyncrestha.github.io
  github: elwyncrestha
  linkedin: elvin-shrestha-a559a6156
  facebook: elwyncrestha
  twitter: elwyncrestha
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: S.B Solutions Pvt Ltd
      location: Kathmandu, Nepal
      title: Associate Developer (Part Timer)
      started: 2019
      duration: (2019 - Present)
      description: Working as Associate Developer (Part Timer), and learning lots of things every day.
    - work2:
      company: S.B Solutions Pvt Ltd
      location: Kathmandu, Nepal
      title: Intern
      started: 2019
      duration: (2019)
      description: Worked as an intern, I'd been learning and developing my skills rapidly since then. With exposure to banking environment, my domain knowledge in business is growing.
  educationHistory:
    - education1:
      organization: Softwarica College of IT & E-commerce (NCC Education)
      location: Dillibazar, Kathmandu
      degree: Level 5 Diploma in Computing
      major: Software Engineering
      started: 2018
      duration: (2018 - 2019)
      description: I've been reading in this college as a second year student.
    - education2:
      organization: Softwarica College of IT & E-commerce (NCC Education)
      location: Dillibazar, Kathmandu
      degree: Level 4 Diploma in Computing
      major: Software Engineering
      started: 2017
      duration: (2017 - 2018)
      description: Obtained score of 76.375%. Coursework includes Designing and Developing Object Oriented Computer Program, Designing and Developing a Website, Computer Networks, Office Solution Developments, Databases, Skills for Computing, Computer System, Software Development Techniques.
    - education3:
      organization: Trinity International College
      location: Dillibazar, Kathmandu
      degree: National Examinations Board (NEB)
      major: Science Faculty with Computer Science
      started: 2015
      duration: (2015 - 2017)
      description: Obtained score of aggregate 78.50%.
    - education3:
      organization: Next Generation Residential Academy
      location: Gagalal Marg, Kathmandu
      degree: School Leaving Certificate (SLC)
      major: SLC
      started: 2003
      duration: (2003 - 2015)
      description: Obtained score of 85.375%.
  languages:
    - language1:
      name: Nepali
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 95%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: Plain PHP
      percentage: 80%
    - skill4:
      name: Java/Java EE
      percentage: 70%
    - skill5:
      name: C#
      percentage: 55%
    - skill6:
      name: MySQL, SQL Server
      percentage: 50%
    - skill7:
      name: JavaScript
      percentage: 45%
    - skill8:
      name: C
      percentage: 45%
  interests:
    - interest1:
      value: Interested in both mobile app development and web development
    - interest2:
      value: Interested in competitive programming.
    - interest3:
      value: To gain the ability to work in fast-paced environment.
    - interest4:
      value: To understand real world problem and learn to deal with it.
    - interest5:
      value: To understand user’s psychology and how users react with different platforms.
    - interest6:
      value: I like automating things, so possibly I'll start ML after few years.
