# Site settings
title: Elvin Shrestha
description: Elvin Shrestha's Curriculum Vitae
favicon: /assets/img/avatar.JPG
baseurl: https://elwyncrestha.github.io
url: https://elwyncrestha.github.io
rss_url: /pages/atom.xml
google_analytics: UA-132466874-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Elvin Shrestha
  title: Java Developer
  address: Tahachal-13, Kathmandu, Nepal
  email: elwyncrestha@gmail.com
  link: https://elwyncrestha.github.io
  github: elwyncrestha
  linkedin: elvin-shrestha-a559a6156
  facebook: elwyncrestha
  twitter: elwyncrestha
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Not Worked Yet
      location: Kathmandu, Nepal
      title: Student
      started: 2019
      duration: (2019 - Present)
      description: I have not worked yet. In search for internship.
  educationHistory:
    - education1:
      organization: Softwarica College of IT & E-commerce (NCC Education)
      location: Dillibazar, Kathmandu
      degree: Level 5 Diploma in Computing
      major: Software Engineering
      started: 2018
      duration: (2018 - 2019)
      description: I've been reading in this college as a second year student.
    - education2:
      organization: Softwarica College of IT & E-commerce (NCC Education)
      location: Dillibazar, Kathmandu
      degree: Level 4 Diploma in Computing
      major: Software Engineering
      started: 2017
      duration: (2017 - 2018)
      description: Obtained score of 76.375%. Coursework includes Designing and Developing Object Oriented Computer Program, Designing and Developing a Website, Computer Networks, Office Solution Developments, Databases, Skills for Computing, Computer System, Software Development Techniques
  languages:
    - language1:
      name: Nepali
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 30%
    - skill4:
      name: Java/Java EE
      percentage: 80%
    - skill5:
      name: PHP
      percentage: 90%
    - skill6:
      name: C#
      percentage: 70%
